// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAusnRxlxNmiuhTT536bXsUSsuBKmje3Bw',
    appId: '1:745826634629:web:72f05e7bd566a204f412ec',
    messagingSenderId: '745826634629',
    projectId: 'logistics-now',
    authDomain: 'logistics-now.firebaseapp.com',
    storageBucket: 'logistics-now.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkzR2vuArSrBFPKQEXu_84v0HA7-paN5U',
    appId: '1:745826634629:android:80e872da18a831c4f412ec',
    messagingSenderId: '745826634629',
    projectId: 'logistics-now',
    storageBucket: 'logistics-now.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuOWrxt3TOdf-ec1fW-ArXqBDjEXjV6dg',
    appId: '1:745826634629:ios:0bcb5a414f7e3ab0f412ec',
    messagingSenderId: '745826634629',
    projectId: 'logistics-now',
    storageBucket: 'logistics-now.appspot.com',
    iosBundleId: 'com.example.logisticsNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuOWrxt3TOdf-ec1fW-ArXqBDjEXjV6dg',
    appId: '1:745826634629:ios:d6a8f3b30f02674ff412ec',
    messagingSenderId: '745826634629',
    projectId: 'logistics-now',
    storageBucket: 'logistics-now.appspot.com',
    iosBundleId: 'com.example.logisticsNow.RunnerTests',
  );
}
